// Replace 'REPLICATION_USER', 'MONITORING_BOX', 'REPLICATION_PASS', 'READ_ONLY_PASS', 'READ_ONLY_USER', 'HEARTBEAT_USER' and 'HEARTBEAT_PASS', then execute this SQL as root on the master, slave, and monitoring server

GRANT REPLICATION SLAVE, REPLICATION CLIENT, SUPER ON *.* TO 'REPLICATION_USER'@"localhost" IDENTIFIED BY 'REPLICATION_PASS';
GRANT REPLICATION SLAVE, REPLICATION CLIENT, SUPER ON *.* TO 'REPLICATION_USER'@"MONITORING_BOX" IDENTIFIED BY 'REPLICATION_PASS';

GRANT SELECT, REPLICATION CLIENT ON *.* TO 'READ_ONLY_USER'@"localhost" IDENTIFIED BY 'READ_ONLY_PASS';
GRANT SELECT, REPLICATION CLIENT ON *.* TO 'READ_ONLY_USER'@"MONITORING_BOX" IDENTIFIED BY 'READ_ONLY_PASS';

GRANT SELECT, INSERT, UPDATE, ALTER ON replication_monitor.* TO 'HEARTBEAT_USER'@"localhost" IDENTIFIED BY 'HEARTBEAT_PASS';
GRANT SELECT, INSERT, UPDATE, ALTER ON replication_monitor.* TO 'HEARTBEAT_USER'@"MONITORING_BOX" IDENTIFIED BY 'HEARTBEAT_PASS';

CREATE DATABASE replication_monitor;

CREATE TABLE replication_monitor.heartbeats (
  unix_time INTEGER NOT NULL, 
  db_time TIMESTAMP NOT NULL, 
  INDEX time_idx(unix_time)
)